export interface District {
  id: string;
  name: string;
  division: string;
  description: string;
  famousPlaces: string[];
  famousFoods: string[];
  image: string;
  rating: number;
  coordinates: {
    lat: number;
    lng: number;
  };
}

export const divisions = [
  "All",
  "Dhaka",
  "Chittagong",
  "Rajshahi",
  "Khulna",
  "Barisal",
  "Sylhet",
  "Rangpur",
  "Mymensingh",
];

export const districts: District[] = [
  // Dhaka Division
  {
    id: "1",
    name: "Dhaka",
    division: "Dhaka",
    description:
      "The capital and largest city of Bangladesh, known for its vibrant culture, historical sites, and bustling markets.",
    famousPlaces: [
      "Lalbagh Fort",
      "Ahsan Manzil",
      "Dhakeshwari Temple",
      "National Parliament House",
      "Sadarghat",
    ],
    famousFoods: [
      "Kacchi Biryani",
      "Morog Polao",
      "Shahi Tukra",
      "Borhani",
      "Haleem",
    ],
    image: "https://images.unsplash.com/photo-1629473210419-3f0406856525?w=800",
    rating: 4.7,
    coordinates: { lat: 23.8103, lng: 90.4125 },
  },
  {
    id: "2",
    name: "Faridpur",
    division: "Dhaka",
    description:
      "Known for its agricultural lands and the historic Mathbaria Zamindar Bari.",
    famousPlaces: [
      "Mathbaria Zamindar Bari",
      "Faridpur Rajbari",
      "Padma River",
      "Dutch Cemetery",
    ],
    famousFoods: ["Rasgulla", "Chomchom", "Roshmalai", "Pantua", "Hilsa Fish"],
    image: "https://images.unsplash.com/photo-1596895111956-bf1cf0599ce5?w=800",
    rating: 4.2,
    coordinates: { lat: 23.607, lng: 89.8429 },
  },
  {
    id: "3",
    name: "Gazipur",
    division: "Dhaka",
    description:
      "Industrial hub with beautiful parks and the famous Bhawal National Park.",
    famousPlaces: [
      "Bhawal National Park",
      "Bangabandhu Safari Park",
      "Nuhash Palli",
      "Joy Devpur",
    ],
    famousFoods: ["Doi", "Pitha", "Khichuri", "Beef Curry", "Jhal Muri"],
    image: "https://images.unsplash.com/photo-1603504445851-4e4bf51aee2b?w=800",
    rating: 4.3,
    coordinates: { lat: 24.0022, lng: 90.4264 },
  },
  {
    id: "4",
    name: "Gopalganj",
    division: "Dhaka",
    description:
      "Birthplace of Bangabandhu Sheikh Mujibur Rahman, with rich history and rural beauty.",
    famousPlaces: [
      "Bangabandhu Memorial Museum",
      "Ulpur",
      "Gopalganj Sadar",
      "Madhumati River",
    ],
    famousFoods: [
      "Pitha",
      "Payesh",
      "Khoi",
      "Date Palm Jaggery",
      "River Fish Curry",
    ],
    image: "https://images.unsplash.com/photo-1628189870104-d53b9222c36a?w=800",
    rating: 4.1,
    coordinates: { lat: 23.005, lng: 89.8266 },
  },
  {
    id: "5",
    name: "Kishoreganj",
    division: "Dhaka",
    description:
      "Known for Haor areas, rich culture, and the historic Isha Khan's Fort.",
    famousPlaces: [
      "Haor Areas",
      "Nikli Haor",
      "Chandrabati's Birthplace",
      "Shola Forest",
    ],
    famousFoods: [
      "Haor Fish",
      "Pitha",
      "Duck Curry",
      "Shrimp Malai Curry",
      "Til Pitha",
    ],
    image: "https://images.unsplash.com/photo-1605218457336-92c4cd86fa6a?w=800",
    rating: 4.4,
    coordinates: { lat: 24.426, lng: 90.7765 },
  },
  {
    id: "6",
    name: "Madaripur",
    division: "Dhaka",
    description:
      "River-blessed district known for its natural beauty and agriculture.",
    famousPlaces: ["Arial Beel", "Padma River", "Madaripur Sadar", "Jhauchar"],
    famousFoods: ["Hilsa Fish", "Pitha", "Khichuri", "Duck Meat", "Doi Katla"],
    image: "https://images.unsplash.com/photo-1622554316682-9f6bd5460597?w=800",
    rating: 4.0,
    coordinates: { lat: 23.1641, lng: 90.1897 },
  },
  {
    id: "7",
    name: "Manikganj",
    division: "Dhaka",
    description:
      "Known for pottery, Jamdani sarees, and the historic Baliati Palace.",
    famousPlaces: [
      "Baliati Palace",
      "Tewta Temple",
      "Paturia Ghat",
      "Padma Bridge Point",
    ],
    famousFoods: ["Moa", "Batasha", "Pitha", "Doi", "Khoi"],
    image: "https://images.unsplash.com/photo-1588668214407-6eb0069651d3?w=800",
    rating: 4.2,
    coordinates: { lat: 23.8617, lng: 90.0003 },
  },
  {
    id: "8",
    name: "Munshiganj",
    division: "Dhaka",
    description: "Ancient Vikrampur region with rich archaeological heritage.",
    famousPlaces: [
      "Idrakpur Fort",
      "Rampal Dighi",
      "Padma River",
      "Atpara Mosque",
    ],
    famousFoods: ["Hilsa Fish", "Katla Fish", "Pitha", "Rui Curry", "Khichuri"],
    image: "https://images.unsplash.com/photo-1606229338636-d76077977eb8?w=800",
    rating: 4.1,
    coordinates: { lat: 23.5422, lng: 90.5305 },
  },
  {
    id: "9",
    name: "Narayanganj",
    division: "Dhaka",
    description:
      "Industrial city known as Dundee of Bangladesh, famous for textiles and jute mills.",
    famousPlaces: ["Panam City", "Sonargaon", "Goaldi Mosque", "Hajiganj Fort"],
    famousFoods: ["Biryani", "Kabab", "Bakarkhani", "Shahi Tukra", "Haleem"],
    image: "https://images.unsplash.com/photo-1582650630656-7492c68c2273?w=800",
    rating: 4.3,
    coordinates: { lat: 23.6238, lng: 90.5 },
  },
  {
    id: "10",
    name: "Narsingdi",
    division: "Dhaka",
    description:
      "Known for its textile industry and the historic Wari-Bateshwar archaeological site.",
    famousPlaces: [
      "Wari-Bateshwar",
      "Meghna River",
      "Narsingdi Sadar",
      "Hasnabad",
    ],
    famousFoods: ["Pitha", "Khichuri", "Hilsa Fish", "Koi Fish", "Doi"],
    image: "https://images.unsplash.com/photo-1619266465172-02a857c3556d?w=800",
    rating: 4.0,
    coordinates: { lat: 23.9229, lng: 90.7179 },
  },
  {
    id: "11",
    name: "Rajbari",
    division: "Dhaka",
    description: "Known for its mangoes, historic structures, and Padma River.",
    famousPlaces: [
      "Rajbari Sadar",
      "Padma River",
      "Goalanda Ghat",
      "Baliakandi",
    ],
    famousFoods: ["Mango", "Hilsa Fish", "Pitha", "Khichuri", "Langcha"],
    image: "https://images.unsplash.com/photo-1591871937573-74dbba515c4c?w=800",
    rating: 4.1,
    coordinates: { lat: 23.7574, lng: 89.6444 },
  },
  {
    id: "12",
    name: "Shariatpur",
    division: "Dhaka",
    description:
      "Riverine district known for its natural beauty and agriculture.",
    famousPlaces: ["Padma River", "Naria", "Shariatpur Sadar", "Jazira"],
    famousFoods: ["Hilsa Fish", "Pitha", "Duck Curry", "Doi Katla", "Khichuri"],
    image: "https://images.unsplash.com/photo-1599587282869-7248f76fa968?w=800",
    rating: 4.0,
    coordinates: { lat: 23.2423, lng: 90.4348 },
  },
  {
    id: "13",
    name: "Tangail",
    division: "Dhaka",
    description:
      "Famous for Tangail sarees, Madhupur forest, and rich cultural heritage.",
    famousPlaces: [
      "Madhupur National Park",
      "Atia Mosque",
      "Mohera Zamindar Bari",
      "Jamuna Bridge",
    ],
    famousFoods: [
      "Tangail Chamcham",
      "Pitha",
      "Doi",
      "Nakshi Pitha",
      "Chomchom",
    ],
    image: "https://images.unsplash.com/photo-1600609842388-34818128362d?w=800",
    rating: 4.5,
    coordinates: { lat: 24.2513, lng: 89.9167 },
  },

  // Chittagong Division
  {
    id: "14",
    name: "Chittagong",
    division: "Chittagong",
    description:
      "Major port city with beautiful beaches, hills, and rich cultural diversity.",
    famousPlaces: [
      "Cox's Bazar",
      "Patenga Beach",
      "Foy's Lake",
      "Ethnological Museum",
      "Chittagong Port",
    ],
    famousFoods: [
      "Mezban",
      "Shatkora Beef",
      "Shutki Bhorta",
      "Fried Fish",
      "Chatpati",
    ],
    image: "https://images.unsplash.com/photo-1585223388863-7e23d38c642e?w=800",
    rating: 4.8,
    coordinates: { lat: 22.3569, lng: 91.7832 },
  },
  {
    id: "15",
    name: "Cox's Bazar",
    division: "Chittagong",
    description:
      "Home to the world's longest natural sea beach and breathtaking sunsets.",
    famousPlaces: [
      "Cox's Bazar Beach",
      "Inani Beach",
      "Himchari",
      "Marine Drive",
      "Saint Martin's Island",
    ],
    famousFoods: [
      "Shutki",
      "Fried Fish",
      "Lobster",
      "Crab Curry",
      "Chitol Fish",
    ],
    image: "https://images.unsplash.com/photo-1595166661749-3c306d157ccf?w=800",
    rating: 4.9,
    coordinates: { lat: 21.4272, lng: 92.0058 },
  },
  {
    id: "16",
    name: "Bandarban",
    division: "Chittagong",
    description:
      "Hill district with stunning mountain views, tribal culture, and waterfalls.",
    famousPlaces: [
      "Nilgiri",
      "Boga Lake",
      "Nafakhum Waterfall",
      "Golden Temple",
      "Sangu River",
    ],
    famousFoods: [
      "Bamboo Chicken",
      "Tribal Rice Beer",
      "Smoked Pork",
      "Hill Chicken",
      "Sidol",
    ],
    image: "https://images.unsplash.com/photo-1587974928442-77dc3207cc2e?w=800",
    rating: 4.9,
    coordinates: { lat: 22.1953, lng: 92.2183 },
  },
  {
    id: "17",
    name: "Rangamati",
    division: "Chittagong",
    description:
      "Lake district known for Kaptai Lake, hanging bridges, and indigenous culture.",
    famousPlaces: [
      "Kaptai Lake",
      "Hanging Bridge",
      "Shuvolong Waterfall",
      "Rajban Vihara",
      "Chakma Rajbari",
    ],
    famousFoods: [
      "Bamboo Shoot Curry",
      "Nappi",
      "Sidol",
      "Hill Rice",
      "Tribal Dishes",
    ],
    image: "https://images.unsplash.com/photo-1633633640244-a62c5565576f?w=800",
    rating: 4.8,
    coordinates: { lat: 22.7324, lng: 92.2985 },
  },
  {
    id: "18",
    name: "Khagrachhari",
    division: "Chittagong",
    description:
      "Hill district with scenic beauty, waterfalls, and tribal diversity.",
    famousPlaces: [
      "Alutila Cave",
      "Risang Waterfall",
      "Taung Lake",
      "Hanging Bridge",
    ],
    famousFoods: [
      "Bamboo Chicken",
      "Hill Vegetables",
      "Tribal Pitha",
      "Smoked Meat",
      "Sidol",
    ],
    image: "https://images.unsplash.com/photo-1605626292398-3330616900f3?w=800",
    rating: 4.6,
    coordinates: { lat: 23.1193, lng: 91.9847 },
  },
  {
    id: "19",
    name: "Comilla",
    division: "Chittagong",
    description:
      "Known for archaeological sites, roshomalai sweets, and historical monuments.",
    famousPlaces: [
      "Mainamati Ruins",
      "Shalban Vihara",
      "War Cemetery",
      "Comilla Cantonment",
    ],
    famousFoods: ["Roshomalai", "Khirsha", "Doi", "Pantua", "Kheer"],
    image: "https://images.unsplash.com/photo-1579363597652-5a9d685542b8?w=800",
    rating: 4.5,
    coordinates: { lat: 23.4607, lng: 91.1809 },
  },
  {
    id: "20",
    name: "Chandpur",
    division: "Chittagong",
    description:
      "River junction district known for hilsa fish and river transport.",
    famousPlaces: [
      "Meghna River",
      "Padma River",
      "Chandpur Launch Terminal",
      "Hajiganj",
    ],
    famousFoods: [
      "Hilsa Fish",
      "Pitha",
      "Fish Curry",
      "Duck Curry",
      "Doi Katla",
    ],
    image: "https://images.unsplash.com/photo-1585694723821-4d1e2da7b9a7?w=800",
    rating: 4.2,
    coordinates: { lat: 23.2332, lng: 90.6712 },
  },
  {
    id: "21",
    name: "Brahmanbaria",
    division: "Chittagong",
    description:
      "Known for its educated population, religious harmony, and Titas River.",
    famousPlaces: ["Titas River", "Brahmanbaria Sadar", "Akhaura", "Bibirhat"],
    famousFoods: ["Pitha", "Doi", "Khichuri", "Fish Curry", "Pantua"],
    image: "https://images.unsplash.com/photo-1627920769830-4c3214541579?w=800",
    rating: 4.3,
    coordinates: { lat: 23.9571, lng: 91.1119 },
  },
  {
    id: "22",
    name: "Feni",
    division: "Chittagong",
    description:
      "Known for its cane furniture, mustard oil, and historical significance.",
    famousPlaces: ["Feni River", "Shaheed Minar", "Feni Sadar", "Daganbhuiyan"],
    famousFoods: ["Mustard Oil", "Pitha", "Doi", "Fish Curry", "Khichuri"],
    image: "https://images.unsplash.com/photo-1594957639517-814231b4097f?w=800",
    rating: 4.1,
    coordinates: { lat: 23.0159, lng: 91.3976 },
  },
  {
    id: "23",
    name: "Lakshmipur",
    division: "Chittagong",
    description:
      "Coastal district known for fishing industry and natural beauty.",
    famousPlaces: [
      "Meghna River",
      "Char Alexander",
      "Lakshmipur Sadar",
      "Ramgati",
    ],
    famousFoods: ["Hilsa Fish", "Dry Fish", "Pitha", "Fish Curry", "Doi"],
    image: "https://images.unsplash.com/photo-1599587282869-7248f76fa968?w=800",
    rating: 4.0,
    coordinates: { lat: 22.9447, lng: 90.8282 },
  },
  {
    id: "24",
    name: "Noakhali",
    division: "Chittagong",
    description:
      "Coastal district known for natural disasters resilience and char lands.",
    famousPlaces: [
      "Nijhum Dwip",
      "Sonapur Beach",
      "Maijdee Court",
      "Char areas",
    ],
    famousFoods: [
      "Shutki",
      "Hilsa Fish",
      "Pitha",
      "Dry Fish Bhorta",
      "Duck Curry",
    ],
    image: "https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800",
    rating: 4.2,
    coordinates: { lat: 22.8724, lng: 91.0973 },
  },

  // Rajshahi Division
  {
    id: "25",
    name: "Rajshahi",
    division: "Rajshahi",
    description:
      "City of silk and mangoes, known for its educational institutions and Padma River.",
    famousPlaces: [
      "Varendra Research Museum",
      "Puthia Rajbari",
      "Padma Garden",
      "Barendra Museum",
    ],
    famousFoods: ["Mango", "Silk", "Chomchom", "Langcha", "Pitha"],
    image: "https://images.unsplash.com/photo-1607592476483-c21d7b3260c6?w=800",
    rating: 4.6,
    coordinates: { lat: 24.3745, lng: 88.6042 },
  },
  {
    id: "26",
    name: "Bogra",
    division: "Rajshahi",
    description:
      "Ancient city with archaeological sites, including Mahasthangarh.",
    famousPlaces: [
      "Mahasthangarh",
      "Gokul Medh",
      "Kherua Mosque",
      "Mahasthan Museum",
    ],
    famousFoods: ["Doi (Yogurt)", "Misti", "Pitha", "Khichuri", "Beef Curry"],
    image: "https://images.unsplash.com/photo-1580227183017-da4b74542289?w=800",
    rating: 4.5,
    coordinates: { lat: 24.8465, lng: 89.377 },
  },
  {
    id: "27",
    name: "Chapainawabganj",
    division: "Rajshahi",
    description: "Known for mangoes, Sona Mosque, and archaeological heritage.",
    famousPlaces: [
      "Sona Mosque",
      "Tahirpur",
      "Kansat Mango Market",
      "Rohanpur",
    ],
    famousFoods: ["Fazli Mango", "Langra Mango", "Misti", "Pitha", "Khichuri"],
    image: "https://images.unsplash.com/photo-1627660237937-41484860cc22?w=800",
    rating: 4.4,
    coordinates: { lat: 24.5965, lng: 88.2775 },
  },
  {
    id: "28",
    name: "Joypurhat",
    division: "Rajshahi",
    description: "Known for its archaeological sites and rice production.",
    famousPlaces: ["Joypurhat Sadar", "Panchbibi", "Archaeological sites"],
    famousFoods: ["Rice", "Pitha", "Doi", "Misti", "Khichuri"],
    image: "https://images.unsplash.com/photo-1585123388867-3bfe6dd4bdbf?w=800",
    rating: 4.1,
    coordinates: { lat: 25.0968, lng: 89.0227 },
  },
  {
    id: "29",
    name: "Naogaon",
    division: "Rajshahi",
    description:
      "Home to Paharpur Buddhist Monastery, a UNESCO World Heritage Site.",
    famousPlaces: [
      "Paharpur",
      "Somapura Mahavihara",
      "Naogaon Sadar",
      "Patnitala",
    ],
    famousFoods: ["Pitha", "Doi", "Khichuri", "Misti", "Beef Curry"],
    image: "https://images.unsplash.com/photo-1600100742133-c98565751969?w=800",
    rating: 4.7,
    coordinates: { lat: 24.8132, lng: 88.9293 },
  },
  {
    id: "30",
    name: "Natore",
    division: "Rajshahi",
    description: "Known for Uttara Gono Bhaban and historic Rajbaris.",
    famousPlaces: [
      "Uttara Gono Bhaban",
      "Natore Rajbari",
      "Rani Bhabani's Palace",
      "Dighapatia Rajbari",
    ],
    famousFoods: ["Kachagolla", "Misti", "Pitha", "Doi", "Langcha"],
    image: "https://images.unsplash.com/photo-1597527187114-142279774673?w=800",
    rating: 4.3,
    coordinates: { lat: 24.4206, lng: 88.9954 },
  },
  {
    id: "31",
    name: "Pabna",
    division: "Rajshahi",
    description:
      "Known for its mental hospital, handloom industry, and Padma River.",
    famousPlaces: [
      "Hardinge Bridge",
      "Pabna Mental Hospital",
      "Padma River",
      "Paksey",
    ],
    famousFoods: ["Khirsha", "Pitha", "Doi", "Misti", "Khichuri"],
    image: "https://images.unsplash.com/photo-1598003185522-6b99de07920e?w=800",
    rating: 4.2,
    coordinates: { lat: 24.0064, lng: 89.2372 },
  },
  {
    id: "32",
    name: "Sirajganj",
    division: "Rajshahi",
    description:
      "Known for the Bangabandhu Bridge and agricultural production.",
    famousPlaces: [
      "Bangabandhu Bridge",
      "Jamuna River",
      "Sirajganj Sadar",
      "Kazipur",
    ],
    famousFoods: ["Pitha", "Doi", "Khichuri", "Fish Curry", "Misti"],
    image: "https://images.unsplash.com/photo-1563729784474-d77ddb932400?w=800",
    rating: 4.3,
    coordinates: { lat: 24.4533, lng: 89.7006 },
  },

  // Khulna Division
  {
    id: "33",
    name: "Khulna",
    division: "Khulna",
    description:
      "Gateway to the Sundarbans, known for shipbuilding and shrimp industry.",
    famousPlaces: [
      "Sundarbans",
      "Sixty Dome Mosque",
      "Mongla Port",
      "Khan Jahan Ali's Tomb",
    ],
    famousFoods: [
      "Chingri Malai Curry",
      "Kakra (Crab)",
      "Rupchanda Fish",
      "Pitha",
      "Bhapa Ilish",
    ],
    image: "https://images.unsplash.com/photo-1592661836104-58525b3060d4?w=800",
    rating: 4.7,
    coordinates: { lat: 22.8456, lng: 89.5403 },
  },
  {
    id: "34",
    name: "Bagerhat",
    division: "Khulna",
    description: "UNESCO World Heritage Site with historic mosques and tombs.",
    famousPlaces: [
      "Sixty Dome Mosque",
      "Khan Jahan Ali's Tomb",
      "Nine Dome Mosque",
      "Sundarbans",
    ],
    famousFoods: ["Prawn Curry", "Fish Curry", "Pitha", "Doi", "Khichuri"],
    image: "https://images.unsplash.com/photo-1586326176508-4127598c1569?w=800",
    rating: 4.8,
    coordinates: { lat: 22.6602, lng: 89.7895 },
  },
  {
    id: "35",
    name: "Chuadanga",
    division: "Khulna",
    description: "Known for its mango production and the historic Damurhuda.",
    famousPlaces: ["Chuadanga Sadar", "Damurhuda", "Alamdanga", "Jibannagar"],
    famousFoods: ["Mango", "Pitha", "Doi", "Khichuri", "Langcha"],
    image: "https://images.unsplash.com/photo-1598858178144-803ccb646c0d?w=800",
    rating: 4.0,
    coordinates: { lat: 23.6402, lng: 88.841 },
  },
  {
    id: "36",
    name: "Jessore",
    division: "Khulna",
    description:
      "Known for flowers, date molasses, and the historic Jessore Road.",
    famousPlaces: [
      "Jessore Airport",
      "Chanchara",
      "Michael Madhusudan Dutt's House",
      "Jessore Sadar",
    ],
    famousFoods: [
      "Khejur Gur (Date Molasses)",
      "Pitha",
      "Sandesh",
      "Doi",
      "Langcha",
    ],
    image: "https://images.unsplash.com/photo-1557992260-ec58e38d363c?w=800",
    rating: 4.4,
    coordinates: { lat: 23.1634, lng: 89.2182 },
  },
  {
    id: "37",
    name: "Jhenaidah",
    division: "Khulna",
    description: "Agricultural district known for its peaceful environment.",
    famousPlaces: ["Jhenaidah Sadar", "Maheshpur", "Kaliganj", "Kotchandpur"],
    famousFoods: ["Pitha", "Doi", "Khichuri", "Misti", "Date Palm Jaggery"],
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800",
    rating: 4.1,
    coordinates: { lat: 23.545, lng: 89.1539 },
  },
  {
    id: "38",
    name: "Kushtia",
    division: "Khulna",
    description: "Birthplace of Lalon Shah, known for Baul music and culture.",
    famousPlaces: [
      "Lalon Shah's Shrine",
      "Tagore's Lodge",
      "Kushtia Sadar",
      "Hardinge Bridge",
    ],
    famousFoods: ["Pitha", "Khirsha", "Doi", "Misti", "Khichuri"],
    image: "https://images.unsplash.com/photo-1598387993441-a364f854c3e1?w=800",
    rating: 4.5,
    coordinates: { lat: 23.9012, lng: 89.1199 },
  },
  {
    id: "39",
    name: "Magura",
    division: "Khulna",
    description: "Peaceful district known for agriculture and rural beauty.",
    famousPlaces: ["Magura Sadar", "Mohammadpur", "Shalikha", "Sreepur"],
    famousFoods: ["Pitha", "Doi", "Khichuri", "Misti", "Fish Curry"],
    image: "https://images.unsplash.com/photo-1500964757637-c85e8a162699?w=800",
    rating: 4.0,
    coordinates: { lat: 23.4855, lng: 89.4198 },
  },
  {
    id: "40",
    name: "Meherpur",
    division: "Khulna",
    description:
      "Historic district where Bangladesh's first government was formed.",
    famousPlaces: [
      "Mujibnagar Memorial",
      "Meherpur Sadar",
      "Amjhupi",
      "Gangni",
    ],
    famousFoods: ["Pitha", "Doi", "Misti", "Khichuri", "Langcha"],
    image: "https://images.unsplash.com/photo-1599946347371-88a312a7968a?w=800",
    rating: 4.3,
    coordinates: { lat: 23.7622, lng: 88.6318 },
  },
  {
    id: "41",
    name: "Narail",
    division: "Khulna",
    description: "Known for its rivers, agriculture, and peaceful environment.",
    famousPlaces: ["Narail Sadar", "Lohagara", "Kalia", "Chitra River"],
    famousFoods: ["Fish Curry", "Pitha", "Doi", "Khichuri", "Duck Curry"],
    image: "https://images.unsplash.com/photo-1583096114844-065d1673322d?w=800",
    rating: 4.1,
    coordinates: { lat: 23.1163, lng: 89.484 },
  },
  {
    id: "42",
    name: "Satkhira",
    division: "Khulna",
    description: "Gateway to the Sundarbans, known for shrimp farming.",
    famousPlaces: ["Sundarbans", "Satkhira Sadar", "Shyamnagar", "Kaliganj"],
    famousFoods: ["Prawn", "Crab", "Fish Curry", "Pitha", "Bhapa Ilish"],
    image: "https://images.unsplash.com/photo-1589990886869-d41f71dfb256?w=800",
    rating: 4.4,
    coordinates: { lat: 22.7185, lng: 89.0705 },
  },

  // Barisal Division
  {
    id: "43",
    name: "Barisal",
    division: "Barisal",
    description:
      "City of rivers, known for Barisal guns phenomenon and floating markets.",
    famousPlaces: [
      "Durga Sagar",
      "Oxford Mission",
      "Guthia Mosque",
      "Kirtonkhola River",
    ],
    famousFoods: [
      "Narikel Naru",
      "Pitha",
      "Khirsha",
      "Hilsa Fish",
      "Doi Katla",
    ],
    image: "https://images.unsplash.com/photo-1582239339070-1372722b5e3c?w=800",
    rating: 4.5,
    coordinates: { lat: 22.701, lng: 90.3535 },
  },
  {
    id: "44",
    name: "Barguna",
    division: "Barisal",
    description: "Coastal district known for beaches and natural beauty.",
    famousPlaces: ["Sonar Char", "Taltali Beach", "Barguna Sadar", "Amtali"],
    famousFoods: ["Hilsa Fish", "Shutki", "Pitha", "Fish Curry", "Dry Fish"],
    image: "https://images.unsplash.com/photo-1591871937573-74dbba515c4c?w=800",
    rating: 4.2,
    coordinates: { lat: 22.1595, lng: 90.1121 },
  },
  {
    id: "45",
    name: "Bhola",
    division: "Barisal",
    description: "Island district known for natural disasters resilience.",
    famousPlaces: ["Char Fasson", "Bhola Sadar", "Daulatkhan", "Meghna River"],
    famousFoods: ["Hilsa Fish", "Pitha", "Fish Curry", "Doi", "Khichuri"],
    image: "https://images.unsplash.com/photo-1628522649363-d14612306915?w=800",
    rating: 4.0,
    coordinates: { lat: 22.6859, lng: 90.6482 },
  },
  {
    id: "46",
    name: "Jhalokathi",
    division: "Barisal",
    description: "Known for floating guava markets and river beauty.",
    famousPlaces: ["Guava Market", "Jhalokathi Sadar", "Rajapur", "Kathalia"],
    famousFoods: ["Guava", "Pitha", "Hilsa Fish", "Doi", "Fish Curry"],
    image: "https://images.unsplash.com/photo-1589405856939-74d754f76263?w=800",
    rating: 4.3,
    coordinates: { lat: 22.6406, lng: 90.1987 },
  },
  {
    id: "47",
    name: "Patuakhali",
    division: "Barisal",
    description: "Coastal district known for Kuakata beach and natural beauty.",
    famousPlaces: [
      "Kuakata Beach",
      "Lebur Char",
      "Sonar Char",
      "Patuakhali Sadar",
    ],
    famousFoods: ["Hilsa Fish", "Dry Fish", "Pitha", "Crab", "Fish Curry"],
    image: "https://images.unsplash.com/photo-1591871937631-2f6505369af9?w=800",
    rating: 4.6,
    coordinates: { lat: 22.3596, lng: 90.3298 },
  },
  {
    id: "48",
    name: "Pirojpur",
    division: "Barisal",
    description: "Known for its rivers, agriculture, and peaceful environment.",
    famousPlaces: ["Pirojpur Sadar", "Nesarabad", "Mathbaria", "Bhandaria"],
    famousFoods: ["Hilsa Fish", "Pitha", "Doi", "Fish Curry", "Khichuri"],
    image: "https://images.unsplash.com/photo-1592329347810-258af7228638?w=800",
    rating: 4.1,
    coordinates: { lat: 22.5841, lng: 89.972 },
  },

  // Sylhet Division
  {
    id: "49",
    name: "Sylhet",
    division: "Sylhet",
    description:
      "Land of tea gardens, known for its natural beauty and spiritual heritage.",
    famousPlaces: [
      "Ratargul Swamp Forest",
      "Jaflong",
      "Lalakhal",
      "Shrine of Hazrat Shah Jalal",
      "Tea Gardens",
    ],
    famousFoods: [
      "Seven Color Tea",
      "Shatkora",
      "Pitha",
      "Tusha Shinni",
      "Hatkhora",
    ],
    image: "https://images.unsplash.com/photo-1598556776374-13617a08e9ca?w=800",
    rating: 4.9,
    coordinates: { lat: 24.8949, lng: 91.8687 },
  },
  {
    id: "50",
    name: "Habiganj",
    division: "Sylhet",
    description:
      "Known for tea gardens, natural gas, and Rema-Kalenga Wildlife Sanctuary.",
    famousPlaces: [
      "Rema-Kalenga Wildlife Sanctuary",
      "Madhobpur Lake",
      "Tea Gardens",
      "Habiganj Sadar",
    ],
    famousFoods: ["Pitha", "Tusha Shinni", "Doi", "Duck Curry", "Shatkora"],
    image: "https://images.unsplash.com/photo-1594142750699-28c117b9b77d?w=800",
    rating: 4.4,
    coordinates: { lat: 24.3745, lng: 91.4156 },
  },
  {
    id: "51",
    name: "Moulvibazar",
    division: "Sylhet",
    description:
      "Known for tea estates, Lawachara National Park, and natural beauty.",
    famousPlaces: [
      "Lawachara National Park",
      "Srimangal",
      "Madhabkunda Waterfall",
      "Tea Gardens",
    ],
    famousFoods: [
      "Seven Color Tea",
      "Pineapple",
      "Pitha",
      "Tusha Shinni",
      "Doi",
    ],
    image: "https://images.unsplash.com/photo-1584829193166-5125345759ce?w=800",
    rating: 4.8,
    coordinates: { lat: 24.4829, lng: 91.7774 },
  },
  {
    id: "52",
    name: "Sunamganj",
    division: "Sylhet",
    description: "Land of haors, known for its unique wetland ecosystem.",
    famousPlaces: [
      "Tanguar Haor",
      "Tahirpur",
      "Niladri Lake",
      "Sunamganj Sadar",
    ],
    famousFoods: ["Haor Fish", "Pitha", "Duck Curry", "Doi", "River Fish"],
    image: "https://images.unsplash.com/photo-1605218457336-92c4cd86fa6a?w=800",
    rating: 4.5,
    coordinates: { lat: 25.0657, lng: 91.395 },
  },

  // Rangpur Division
  {
    id: "53",
    name: "Rangpur",
    division: "Rangpur",
    description:
      "Known for citrus fruits, Tajhat Palace, and rich cultural heritage.",
    famousPlaces: [
      "Tajhat Palace",
      "Carmichael College",
      "Rangpur Zoo",
      "Vindaban Park",
    ],
    famousFoods: ["Kamrangini Chomchom", "Pitha", "Doi", "Misti", "Langcha"],
    image: "https://images.unsplash.com/photo-1587974928442-77dc3207cc2e?w=800",
    rating: 4.5,
    coordinates: { lat: 25.7439, lng: 89.2752 },
  },
  {
    id: "54",
    name: "Dinajpur",
    division: "Rangpur",
    description:
      "Known for litchi, archaeological sites including Kantajew Temple.",
    famousPlaces: [
      "Kantajew Temple",
      "Ramsagar",
      "Nayabad Mosque",
      "Dinajpur Rajbari",
    ],
    famousFoods: ["Litchi", "Pitha", "Doi", "Misti", "Khichuri"],
    image: "https://images.unsplash.com/photo-1600605995576-963b53c7c77c?w=800",
    rating: 4.6,
    coordinates: { lat: 25.6217, lng: 88.6354 },
  },
  {
    id: "55",
    name: "Gaibandha",
    division: "Rangpur",
    description: "Agricultural district known for its rivers and rural beauty.",
    famousPlaces: [
      "Gaibandha Sadar",
      "Sundarganj",
      "Brahmaputra River",
      "Tista Barrage",
    ],
    famousFoods: ["Pitha", "Doi", "Khichuri", "Misti", "Fish Curry"],
    image: "https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=800",
    rating: 4.1,
    coordinates: { lat: 25.3288, lng: 89.543 },
  },
  {
    id: "56",
    name: "Kurigram",
    division: "Rangpur",
    description: "Northern border district known for river erosion challenges.",
    famousPlaces: [
      "Dharla River",
      "Kurigram Sadar",
      "Nageshwari",
      "Bhurungamari",
    ],
    famousFoods: ["Pitha", "Doi", "Fish Curry", "Misti", "Khichuri"],
    image: "https://images.unsplash.com/photo-1563299796-b729d0af54a5?w=800",
    rating: 4.0,
    coordinates: { lat: 25.8073, lng: 89.6298 },
  },
  {
    id: "57",
    name: "Lalmonirhat",
    division: "Rangpur",
    description: "Border district known for agriculture and trade.",
    famousPlaces: ["Lalmonirhat Sadar", "Patgram", "Teesta River", "Aditmari"],
    famousFoods: ["Pitha", "Doi", "Misti", "Khichuri", "Fish Curry"],
    image: "https://images.unsplash.com/photo-1599587282869-7248f76fa968?w=800",
    rating: 4.1,
    coordinates: { lat: 25.9923, lng: 89.2847 },
  },
  {
    id: "58",
    name: "Nilphamari",
    division: "Rangpur",
    description: "Known for Nilsagar and agricultural production.",
    famousPlaces: ["Nilsagar", "Chilahati", "Nilphamari Sadar", "Domar"],
    famousFoods: ["Pitha", "Doi", "Misti", "Khichuri", "Langcha"],
    image: "https://images.unsplash.com/photo-1604537466158-719b1972feb8?w=800",
    rating: 4.2,
    coordinates: { lat: 25.9317, lng: 88.856 },
  },
  {
    id: "59",
    name: "Panchagarh",
    division: "Rangpur",
    description:
      "Northernmost district known for Tetulia, the coldest place in Bangladesh.",
    famousPlaces: [
      "Tetulia",
      "Panchagarh Sadar",
      "Banglabandha",
      "Rocks Museum",
    ],
    famousFoods: ["Pitha", "Doi", "Misti", "Khichuri", "Fish Curry"],
    image: "https://images.unsplash.com/photo-1595180695027-6c22cb154674?w=800",
    rating: 4.3,
    coordinates: { lat: 26.3411, lng: 88.5541 },
  },
  {
    id: "60",
    name: "Thakurgaon",
    division: "Rangpur",
    description:
      "Known for its agricultural production and peaceful environment.",
    famousPlaces: ["Thakurgaon Sadar", "Ranisankail", "Pirganj", "Baliadangi"],
    famousFoods: ["Pitha", "Doi", "Misti", "Khichuri", "Langcha"],
    image: "https://images.unsplash.com/photo-1606787366850-de6330128bfc?w=800",
    rating: 4.0,
    coordinates: { lat: 26.0336, lng: 88.4616 },
  },

  // Mymensingh Division
  {
    id: "61",
    name: "Mymensingh",
    division: "Mymensingh",
    description:
      "Educational hub known for Agricultural University and Brahmaputra River.",
    famousPlaces: [
      "Brahmaputra River",
      "Mymensingh Museum",
      "Shashi Lodge",
      "BAU Campus",
    ],
    famousFoods: ["Monda", "Muktagacha Monda", "Pitha", "Doi", "Khichuri"],
    image: "https://images.unsplash.com/photo-1585123388867-3bfe6dd4bdbf?w=800",
    rating: 4.6,
    coordinates: { lat: 24.7471, lng: 90.4203 },
  },
  {
    id: "62",
    name: "Jamalpur",
    division: "Mymensingh",
    description: "Known for Jamuna River and textile industry.",
    famousPlaces: ["Jamuna River", "Jamalpur Sadar", "Laura", "Islampur"],
    famousFoods: ["Pitha", "Doi", "Khichuri", "Misti", "Fish Curry"],
    image: "https://images.unsplash.com/photo-1598972591605-2b496739d486?w=800",
    rating: 4.2,
    coordinates: { lat: 24.9375, lng: 89.9404 },
  },
  {
    id: "63",
    name: "Netrokona",
    division: "Mymensingh",
    description: "Known for haors, folk music, and natural beauty.",
    famousPlaces: ["Netrokona Sadar", "Durgapur", "Mohanganj", "Haor areas"],
    famousFoods: ["Pitha", "Haor Fish", "Doi", "Duck Curry", "Khichuri"],
    image: "https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=800",
    rating: 4.3,
    coordinates: { lat: 24.8803, lng: 90.7274 },
  },
  {
    id: "64",
    name: "Sherpur",
    division: "Mymensingh",
    description: "Known for Garo Hills and tribal culture.",
    famousPlaces: ["Garo Hills", "Sherpur Sadar", "Nalitabari", "Jhenaigati"],
    famousFoods: ["Tribal Dishes", "Pitha", "Doi", "Fish Curry", "Khichuri"],
    image: "https://images.unsplash.com/photo-1629814457788-517861937533?w=800",
    rating: 4.4,
    coordinates: { lat: 25.0204, lng: 90.0152 },
  },
];
